# Generated by Django 5.0.4 on 2024-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('country_id', models.CharField(max_length=1)),
                ('manufacturer_id', models.CharField(max_length=6)),
                ('number_id', models.CharField(max_length=5)),
            ],
        ),
    ]
