# Generated by Django 5.0.4 on 2024-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
